### ISSUE TITLE
Tailwindcss Advanced Classes: 1-parentheses removed for (@supports, [@media, nth-of-type, ...)

### ISSUE THREAD

**Issue by n4j1Br4ch1D** [n4j1Br4ch1D/postcss-obfuscator#13]
https://tailwindcss.com/docs/hover-focus-and-other-states#supports
#11 #12 
```jsx

      {/* prblm with (*) beign removed */}
      <span class="group-[:nth-of-type(3)_&]:block">9</span>
      <span class="[@supports(display:grid)]:grid">7</span>
      <span class="[@media(any-hover:hover){&:hover}]:opacity-100">12</span>
```
but should work for
```css
.trythis:nth-child(even) {
    background-color: green;
}
```
```jsx
      <span class="trythis">the 3rd</span>
```
